server.port=5596
server.address=0.0.0.0

# configurable paths
log.base.dir=C:/Users/parul.jain2/logs
chart.base.dir=C:/Users/parul.jain2/logs/charts

# outputs
excel.output=LoadTestReport.xlsx
doc.output=LoadTestGraphicalReport.docx
