//log.base.dir=C:/Users/parul.jain2/logs

//chart.base.dir=C:/Users/parul.jain2/logs/charts

//spring.web.resources.static-locations=file:${log.base.dir}/

//excel.output=LoadTestReport.xlsx

//doc.output=LoadTestGraphicalReport.docx
